# Copyright 2014 MedicaSoft LLC USA and Info World SRL
# Licensed under the Apache License, Version 2.0 the "License";
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DOMAIN: "<dns_name>"
MAIL_DOMAIN: "direct.<dns_name>"
#External IP for DOMAIN
EXTERNAL_IP: "<external_ip>"

#Node.js API - host and port used to build resource urls in service responses
API_HOSTNAME: "<dns_name>"
API_PORT: 8085

#Configure Elastic Search host and port used by Nginx and Logstash;
#it can be either an internal host and port (if elasticsearch server is accessible from nginx and logstash with an internal IP / localhost)
#or an external host and port
ELASTICSEARCH_HOST: "127.0.0.1"
ELASTICSEARCH_PORT: "9200"

#Configure Elastic Search url used by Kibana
#it should be the External URL to ElasticSearch (and then the port 80 is FIXED by nginx configuration) e.g. http://external_host:80
ELASTICSEARCH_HTTP_URL: "http://<dns_name>:80"

#kibana
KIBANA_LOGIN_USERNAME: "abelian"
KIBANA_LOGIN_PASSWORD: "password"

#true if abelian is installed on the same machine as the nxt application (db server)
ALL_IN_ONE: false

INSTALL_KIBANA: false
#other paths and settings
SPOOL: "/var/spool/direct"      
TEMP_SQL_PATH: "/home/sql-direct-tmp"
POSTFIX_PASSWORD: "{{lookup('password', 'credentials/postfixpass length=10 chars=ascii_letters,digits')}}"


#postgres
# Settings related to the pg_hba rules
postgresql_default_unix_auth_method: "trust"
postgresql_default_ipv4_auth_method: "md5"
postgresql_default_ipv6_auth_method: "md5"
# Admin user
postgresql_admin_user: "postgres"
# Specify default rules for pg_hba.conf
postgresql_pg_hba_default:
 - { type: local, database: all, role: "{{ postgresql_admin_user }}", address: "", method: "{{ postgresql_default_unix_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
 - { type: host, database: pdns, role: pdns, address: "127.0.0.1/32", method: "md5", comment: 'IPv4 local connections:' }
 - { type: host, database: pdns, role: pdns, address: "::1/128", method: "md5", comment: 'IPv6 local connections:' }
 - { type: host, database: all, role: all, address: "127.0.0.1/32", method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'IPv4 local connections:' }
 - { type: host, database: all, role: all, address: "::1/128", method: "{{ postgresql_default_ipv6_auth_method }}", comment: 'IPv6 local connections:' }

#pdns
pdns_password : "password"
pdns_fill_database : true
