---
- hosts: all
  vars_files:    
    - vars/vars.yml
  sudo: yes  

  tasks:    
   #copy smime
   - name: Copy server files to remote node    
     copy: src=../../src/smime/{{item}} dest=/var/spool/direct/{{item}}
     with_items: 
        - certdisco.py
        - certvld.py
        - crypto.py
        - mdn.py
        - smimercv.py
        - smimesend.py
        
   - name: Set file attributes
     file: path=/var/spool/direct/{{item}} group=direct owner=direct mode=770
     with_items: 
        - certdisco.py
        - certvld.py
        - crypto.py
        - mdn.py
        - smimercv.py
        - smimesend.py
        
    #copy tools
   - name: Copy scripts in {{SPOOL}}/tools folder
     copy: src=../../src/tools/ dest={{SPOOL}}/tools/

   - name: Set execute permissions
     file: path={{SPOOL}}/tools/ recurse=yes owner=direct mode=744 state=directory

   
   #copy api
   - name: Deploy API files
     copy: src=../../src/api/ dest={{SPOOL}}/api/
   #  notify: Restart API

   - name: Copy API config file
     template: src=templates/config.js.j2 dest={{SPOOL}}/api/config.js
   #  notify: Restart API
      
  handlers: 
   # - name: Restart API    
   #   service: name=direct state=restarted  
