#!/usr/bin/python

""" Copyright 2014 MedicaSoft LLC USA and Info World SRL
Licensed under the Apache License, Version 2.0 the "License";
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import sys
import psycopg2
queue_id = sys.argv[1]
recip = sys.argv[2]
sender = sys.argv[3]
msg_orig = open(sys.argv[4],'r')
msg_decr = open(sys.argv[5],'r')
conn = psycopg2.connect(database='maildb', user='direct')
cur = conn.cursor();
cur.execute("INSERT INTO messages(queue_id,recipient,sender,original,msg) VALUES(%s,%s,%s,%s,%s);",(queue_id,recip,sender,msg_orig.read(),msg_decr.read()))
conn.commit() 