     -  name: Generate server certificates for ca - ca.key        
        command: openssl genrsa -out "{{SPOOL}}/ca/ca.key" 2048

     -  name: Generate server certificates for ca - ca.pem        
        command: openssl req -new -x509 -days 365 -subj '/CN='$DOMAIN -key "{{SPOOL}}/ca/ca.key" -out "{{SPOOL}}/ca/ca.pem"


     -  name: Generate server certificates for mail root - direct.key
        command: openssl genrsa -out "{{SPOOL}}/ca/direct.key" 2048

     -  name: Generate server certificates for mail root - direct.csr
        command: openssl req -new -subj "/CN={{MAIL_DOMAIN}}" -key "{{SPOOL}}/ca/direct.key" -out "{{SPOOL}}/ca/direct.csr"

     -  name: Generate server certificates for mail root - direct.pem
        command: openssl x509 -req -days 365 -in "{{SPOOL}}/ca/direct.csr" -CA "{{SPOOL}}/ca/ca.pem" -CAkey "{{SPOOL}}/ca/ca.key" -set_serial 1 -out "{{SPOOL}}/ca/direct.pem" -setalias "Self Signed SMIME" -addtrust emailProtection -addreject clientAuth -addreject serverAuth -trustout


     -  name: Get trust bundle
        command: wget -O "{{SPOOL}}/crl/bbplus.p7b" https://secure.bluebuttontrust.org/p7b.ashx?id=4d9daaf9-384a-e211-8bc3-78e3b5114607

     -  name: Generate bbplus.cer
        command: openssl pkcs7 -print_certs -in "{{SPOOL}}/crl/bbplus.p7b" -inform der -out "{{SPOOL}}/crl/bbplus.cer"

     -  name: Remove bbplus.p7b
        command: rm "{{SPOOL}}/crl/bbplus.p7b"

#cp $SPOOL/ca/ca.pem /vagrant/ # ?

#CERT="$(openssl x509 -in $SPOOL/ca/direct.pem -modulus | awk '
# BEGIN {ORS=" ";OFS=" ";PKIX=1;RSASHA1=5}
# {
#   #PKIX tagkey RSASHA1 – where tagkey is the decimal value of
#   #the last two bytes of the modulus
#   if(NR==1) printf("%d %d %d ",PKIX,strtonum("0x" substr($0,length($0)-3)),RSASHA1); 
#   #skip –--BEGIN CERTIFICATE-----
#   if(NR>3) print l;
#     l=$0;
#}')"
