---
- hosts: all
  vars_files:    
    - vars/vars.yml
  sudo: yes  

  tasks:  
    - include: tasks/prereqs.yml
    - include: tasks/postgres.yml 
    - include: tasks/certificates.yml 
    - include: tasks/pdns.yml user=postgres
    - include: tasks/postfix.yml user=postgres
    - include: tasks/api_install.yml
    - include: tasks/api_deploy.yml
    - include: tasks/elasticsearch.yml
    - include: tasks/logstash.yml
    - include: tasks/kibana.yml
    - include: tasks/nginx.yml
    
  handlers: 
    - include: handlers/handlers.yml
