---
- hosts: all
  vars_files:    
    - vars/vars.yml
  sudo: yes  

  tasks:  
    - include: tasks/prereqs.yml
    - include: tasks/postgres.yml 
    - include: tasks/certificates.yml 
    - include: tasks/pdns.yml user=postgres
    - include: tasks/postfix.yml user=postgres
    - include: tasks/api.yml
    - include: tasks/log.yml
    
  handlers: 
    - include: handlers/handlers.yml
