- name: Deploy API files
  copy: src=../../src/api/ dest={{SPOOL}}/api/

- name: Copy API config file
  template: src=templates/config.js.j2 dest={{SPOOL}}/api/config.js
  
- name: Install the required Node.js packages
  npm: path={{SPOOL}}/api
    
- name: Set Node.js app as Upstart service
  template: src=templates/direct.conf.j2 dest=/etc/init/direct.conf
  
- name: Start Node.js service
  service: name=direct state=started  


