- name: Install openjdk7-jdk
  apt: name=openjdk-7-jdk state=present force=yes

- name: Create directory for elasticsearch
  file: path=/opt/elasticsearch state=directory

- name: Download elasticsearch 1.2.1 deb
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb dest=/opt/elasticsearch/elasticsearch-1.2.1.deb
  
- name: Install elasticsearch 1.2.1  
  apt: deb=/opt/elasticsearch/elasticsearch-1.2.1.deb 
  
- name: Configure elasticsearch
  lineinfile: line="{{item}}" dest=/etc/elasticsearch/elasticsearch.yml state=present
  with_items:
    - "cluster.name: logstash_cluster"
    - "node.name: logstash_node"
  notify:
    - Restart elasticsearch
    
- name: Start ES on boot
  command: sudo update-rc.d elasticsearch defaults 95 10
  
- name: Install python-pip
  apt: name=python-pip state=present
  
- name: Install ES curator  
  pip: name=elasticsearch-curator state=present
  
#TODO # Create /etc/cron.daily/elasticsearch_curator Cron Job  
#- name: Set execute permision on /etc/cron.daily/elasticsearch_curator
#  file: path=/etc/cron.daily/elasticsearch_curator mode=770
  
- name: Download Logstash
  get_url: url=https://download.elasticsearch.org/logstash/logstash/logstash-1.4.1.tar.gz dest=/opt/logstash-1.4.1.tar.gz
  
- name: Uncompress Logstash
  shell: chdir=/opt {{item}} creates=/opt/logstash
  with_items:
    - "tar zxf /opt/logstash-1.4.1.tar.gz"        
    - "mv logstash-1.4.1 logstash"
    #- "rm logstash-*.tar.gz"
  sudo: yes
     
- name: Copy Logstash Init Script
  copy: src=config/logstash/logstash dest=/etc/init.d/logstash  
  notify: 
    - Restart logstash
    
- name: Set Logstash Init Script permissions 
  file: path=/etc/init.d/logstash mode=770

- name: Start Logstash on boot
  command: update-rc.d logstash defaults 96 04

- name: Create Logstash configuration directory
  file: path=/etc/logstash state=directory
  
- name: Copy Logstash configuration file
  copy: src=../src/log/logstash/server.conf dest=/etc/logstash
  notify: 
    - Restart logstash
    
- name: Copy Logstash configuration files
  copy: src={{item}} dest=/opt/logstash/patterns/
  with_fileglob:
    - ../src/log/logstash/grok/*.grok        
  notify: 
    - Restart logstash
    
#TODO # Logrotate job for logstash

- name: Download Kibana
  get_url: url=https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz dest=/opt/kibana-3.1.0.tar.gz
  
- name: Uncompress Kibana
  shell: chdir=/opt {{item}} creates=/opt/kibana
  with_items:
    - "tar zxf /opt/kibana-3.1.0.tar.gz"        
    - "mv kibana-3.1.0 kibana"
    #- "rm kibana-*.tar.gz"
  sudo: yes
 
- name: Configure Kibana elastic search url
  replace: 
    dest=/opt/kibana/config.js
    regexp='elasticsearch:\s"http://"\+window\.location\.hostname\+":9200",'    
    replace='elasticsearch{{':'}} "http://192.168.33.10:9200",'
    
- name: Configure Kibana dashboards json
  replace: 
    dest=/opt/kibana/config.js
    regexp='default\.json'    
    replace='LogDashb.json'
      
- name: Copy Kibana dashboard
  copy: src=../src/log/kibana/LogDashb.json dest=/opt/kibana/app/dashboards/

- name: Install nginx
  apt: name=nginx state=present

- name: Configure nginx
  replace: 
    dest=/etc/nginx/sites-available/default
    regexp='root /usr/share/nginx/html;'    
    replace='root /opt/kibana;'
  notify: Restart nginx
