- name: Update repositories cache 
  apt: update_cache=yes      
 
- name: Install unzip
  apt: name=unzip state=present
 
- name: Create Direct group
  group: name=direct state=present

- name: Create Direct user
  user: name=direct home={{SPOOL}} group=direct    

- name: Create Direct file structure
  file: path={{item}} state=directory group=direct owner=direct mode=770
  with_items:
    - "{{SPOOL}}"
    - "{{SPOOL}}/ca"
    - "{{SPOOL}}/crl"
    - "{{SPOOL}}/api"
    - "{{SPOOL}}/tmp"
    - "{{SPOOL}}/tools"

- name: Copy scripts in {{SPOOL}}/tools folder
  copy: src=../src/tools/ dest={{SPOOL}}/tools/

- name: Set execute permissions
  file: path={{SPOOL}}/tools/ recurse=yes owner=direct mode=744

- name: Add {{SPOOL}}/tools folder to PATH for direct user
  lineinfile: dest=~direct/.bash_profile line='{{item}}' state=present 
  with_items:
    - "PATH=$PATH:{{SPOOL}}/tools"
    - "export PATH"

- name: Install python-pip
  apt: name=python-pip state=present