- name: Deploy API files
  copy: src=../../src/api/ dest={{SPOOL}}/api/ owner=direct

- name: Copy API config file
  template: src=templates/config.js.j2 dest={{SPOOL}}/api/config.js owner=direct
  
- name: Install the required Node.js packages
  npm: path={{SPOOL}}/api
  sudo_user: direct
  
- name: Copy init.d script for Direct
  copy: src=files/direct dest=/etc/init.d/direct mode=0770

- name: Enable Direct service 
  command: chkconfig direct on

- name: Start Direct service  
  service: name=direct state=started