# - name: Deploy API files
  # copy: src=../../src/api/ dest={{SPOOL}}/api/ owner=direct

# - name: Copy API config file
  # template: src=templates/config.js.j2 dest={{SPOOL}}/api/config.js owner=direct
  
# - name: Install the required Node.js packages
  # npm: path={{SPOOL}}/api
  # sudo_user: direct
    
- name: Set Node.js app to run on boot with forever
  template: src=templates/init.d_nodejs dest=/etc/rc.d/init.d/direct owner=direct mode=711

- name: Set Direct service
  command: chkconfig --level 345 direct on
  
- name: Start Node.js service
  command: /etc/rc.d/init.d/direct start  


