- name: Download Kibana
  get_url: url=https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz dest=/opt/kibana-3.1.0.tar.gz
  
- name: Uncompress Kibana
  shell: chdir=/opt {{item}} creates=/opt/kibana
  with_items:
    - "tar zxf /opt/kibana-3.1.0.tar.gz"        
    - "mv kibana-3.1.0 kibana"
    #- "rm kibana-*.tar.gz"
  sudo: yes
 
- name: Configure Kibana 
  template: src=files/kibana_config.js dest=/opt/kibana/config.js mode=774
      
- name: Copy Kibana dashboard
  copy: src=../../src/log/kibana/LogDashb.json dest=/opt/kibana/app/dashboards/ mode=774

