
   - name: Install python development headers (requirement for python-ldap)
     yum: name={{item}} state=present
     with_items: 
     - python-devel
     - openldap-devel
     #- libldap2-dev
     #- libsasl2-dev 
     #- libssl-dev
   
   - name: Install python-ldap (dependencies for Python scripts)
     pip: name=python-ldap state=present

   - name: Install swig (requirement for M2Crypto)
     yum: name=swig state=present

   - name: Install M2Crypto (dependencies for Python scripts)
     pip: name=M2Crypto state=present

   - name: Install other libraries
     yum: name=libpqxx-devel
   
   - name: Install other dependencies for Python scripts         
     pip: name={{item}} state=present
     with_items:
        - psycopg2
        - dnspython
        
   - name: Copy server files to remote node    
     copy: src=../../src/smime/{{item}} dest=/var/spool/direct/{{item}}
     with_items: 
        - certdisco.py
        - certvld.py
        - crypto.py
        - mdn.py
        - smimercv.py
        - smimesend.py
        
   - name: Set path to c_rehash
     command: sed -i -e 's|c_rehash|/var/spool/direct/tools/bin/c_rehash|' /var/spool/direct/tools/anchorlib.py
        
   - name: Set file attributes
     file: path=/var/spool/direct/{{item}} group=direct owner=direct mode=775
     with_items: 
        - certdisco.py
        - certvld.py
        - crypto.py
        - mdn.py
        - smimercv.py
        - smimesend.py