#!/usr/bin/python
import argparse, sys, os, glob, subprocess, anchorlib

CADIR = '/var/spool/direct/ca/trust'

parser = argparse.ArgumentParser(description = 'Import trust anchor')
parser.add_argument('cmd', choices = ['add', 'remove'])
parser.add_argument('-d', '--domain', required = True)
parser.add_argument('-f', '--file')

parms = parser.parse_args()

store = os.path.join(CADIR, parms.domain.lower())
if not os.path.isdir(store):
    os.mkdir(store, 0770)

anchor = None
if parms.file != None:
    anchor = open(parms.file, 'rb').read()
else:
    anchor = sys.stdin.read()

if parms.cmd == 'add':
    anchorlib.add_anchor(anchor, store)
elif parms.cmd == 'remove':
    anchorlib.remove_anchor(anchor, store)